#' Metabolic Diversity Index
#'
#' @param Data a data frame the levels of differente detected  metabolites/compounds -rows-, in different samples -columns-.
#'
#' @description MetDiv calculates METabolic Diversity (Hj) index based on Shannon entropy.
#'
#' @details
#' The metabolic profile diversity is defined as the Shannon entropy using metabolite frequency distribution in a sample (j) -Hj index-. Hj can take any value between zero when only one metabolite is detected up to log2(m), where all m metabolites are detected and accumulates at the same frequency: 1/m.
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#' @return A data frame with the Hj value and number of peaks (compounds) per species
#'
#' @export
#' @importFrom methods hasArg
#' @importFrom stats filter
#'
#' @examples Hj <- MetDiv (Data)

MetDiv <- function(Data){
  #Mssg
  print("This function calculates Shannon entropy as a direct measure of Metabolic Diversity")

  #Warnings
  if (nrow(Data)<ncol(Data)) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  if (is.data.frame(Data) == FALSE) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  #Stop
  if (any(is.na(Data))) {
    stop('NA values MUST be replace with Data[is.na(Data)] <- (min(Data, na.rm=TRUE))/1000000')
  }
  if (exists("Pij_fc") == FALSE) {
    stop('Internal function Pij_fc is not uploaded. Please, check MetPlast_int.R functions are properly uploaded.')
  }

  if (exists("numb_peaks_fc") == FALSE) {
    stop('Internal function numb_peaks_fc is not uploaded. Please, check MetPlast_int.R functions are properly uploaded.')
  }

  # Calculate Hj
  Pij <- Pij_fc (Data)
  Hj <- apply(Pij, MARGIN = 2, FUN = Hj_fc )

  # Number of peaks
  numb_peaks <- numb_peaks_fc (Data)

  # Output generation
  Hj <- cbind (Hj, numb_peaks)
  Hj_df <- as.data.frame (Hj)
  Hj_Sample_df <- setDT(Hj_df, keep.rownames = "Sample")
  Hj_Sample_df$Sample <- sub("\\_?\\.?\\d+", "", Hj_Sample_df$Sample)
  Hj_Sample_df$Sample <- sub("\\..", ".", Hj_Sample_df$Sample)

  print (Hj_Sample_df)
}


#' Metabolic Diversity Plot
#'
#' @param MetDiv_df a data frame from MetDiv()
#' @param ... any other argument
#' @description MetDiv_plot generates a plot that shows the distribution of Hj indexes in the data set.
#' @details
#' MetDiv_plot takes as an input the data frame generated by MetDiv() plotting the distribution of Hj indexes calculated by group of samples (i.e. species).
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#'
#' @return It returns overlapped box and dot plots
#'
#' @export
#'
#' @examples
#' Hj_plot <- MetDiv_plot(MetDiv_df)


MetDiv_plot <- function(MetDiv_df, ...) {

  #Warnings
  if (is.data.frame(MetDiv_df) == FALSE) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  #Stops
  if (hasArg(MetDiv_df) == FALSE) {
    stop('MetDiv_df should be provided. Please, run and store MetDiv(). MetDiv_df <- MetDiv()')
  }

  ggplot2::ggplot(MetDiv_df, aes(x=.data[["Hj"]], y = .data[["Sample"]], color =.data[["Sample"]])) + geom_boxplot() + geom_point()
}


#' Metabolic Diversity Supporting Plots
#'
#' @param MetDiv_df a data frame from MetDiv()
#' @param y_element column names from MetDiv_df: "Sample" or "Hj"
#' @param ... any other argument
#'
#' @description MetDiv_Supp_plot can generates 2 plots that shows the depedency of the detect compounds with Samples or Hj.
#' @details
#' MetDiv_plot takes as an input the data frame generated by MetDiv() plotting the relationship between the number of detected compounds and the samples (i.e. species), or Hj index .
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#' @return It returns dot plots
#'
#'
#' @export
#'
#' @examples
#' MetDiv_Supp_plot <- MetDiv_Supp_plot(MetDiv_df = Hj, y_element = Sample)


MetDiv_Supp_plot <- function(MetDiv_df, y_element, ...) {
  #Mssg
  print("This function creates a plot with number of peaks per sample as x element")

  #Warnings
  if (is.data.frame(MetDiv_df) == FALSE) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  #Stops
  if (hasArg(MetDiv_df) == FALSE) {
    stop('MetDiv_df should be provided. Please, run and store MetDiv(). MetDiv_df <- MetDiv()')
  }

  if (hasArg("y_element") == FALSE) {
    stop('Please, provide y element: Sample, Hj')
  }

  ggplot2::ggplot(MetDiv_df, aes(x=.data[["numb_peaks"]], y = {{ y_element }}, color =.data[["Sample"]])) + geom_point()
}


#' Metabolite (Si) Specialization Index
#'
#' @param Data a data frame the levels of differente detected  metabolites/compounds -rows-, in different samples -columns-.
#' @description Si_index calculates METabolite SPECialization (Si) index based on Shannon entropy.
#'
#' @details
#' Metabolic specificity (Si) is defined as the specificity of a particular metabolite (i) among a set of samples (j).
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#' @return It returns a data frame with the Si value per compound
#'
#' @export
#'
#' @examples Si_df <- Si_index (Data)


Si_index <- function (Data){
  # Mssg
  print("THIS PARAMETER CAN NOT BE EXTRAPOLATED TO OTHER DATA SETS")

  #Warnings
  if (nrow(Data)<ncol(Data)) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  if (is.data.frame(Data) == FALSE) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  #Stop
  if (any(is.na(Data))) {
    stop('NA values MUST be replace with Data[is.na(Data)] <- (min(Data, na.rm=TRUE))/1000000')
  }
  if (exists("Pij_by_Pi_fc") == FALSE) {
    stop('Internal function Pij_by_Pi_fc is not uploaded. Please, check MetPlast_int.R functions are properly uploaded.')
  }

  if (exists("Si_fc") == FALSE) {
    stop('Internal function Si_fc is not uploaded. Please, check MetPlast_int.R functions are properly uploaded.')
  }

  # Calculate metabolite specialization
  Pij_by_Pi <- Pij_by_Pi_fc (Data)
  Si <- apply(Pij_by_Pi, MARGIN = 1, FUN = Si_fc)

  # Ouput metabolite specialization
  Si_df <- data.frame (Si)
  Si_df <- setDT(Si_df, keep.rownames = "Compound")
  print(Si_df)
}

#' Metabolite (Si) Specialization Index Plot
#'
#' @param Si_df a data frame with the Si values -column- for all the detected compounds - rows-, calculated from Si_index()
#' @param ... any other argument
#'
#' @description Si_index_plot plots the METabolite SPECialization (Si) indexes based on Shannon entropy for each compound.
#'
#' @details
#' Metabolic specificity (Si) plot generates a graph that shows the distrubution of Si index among a the set of detected compounds (i).
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#' @return It returns a dot plot
#'
#'
#' @export
#'
#' @examples Si_plot <- Si_index_plot (Si_df)

Si_index_plot <- function(Si_df, ...) {
  #Warnings
  if (is.data.frame(Si_df) == FALSE) {
    warning('Si_index_plot functions takes as Si_df argument a data frame')
  }

  #Stops
  if (exists("Si_df") == FALSE) {
    stop('Si_df should be provided. Please, run and store Si_index(). Si_df <- Si_index()')
  }

  ggplot2::ggplot(Si_df, aes(x=.data[["Compound"]], y = .data[["Si"]])) + geom_point()

}

#' Metabolome (δj) Specialization Index
#'
#' @param Data a data frame the levels of differente detected  metabolites/compounds -rows-, in different samples -columns-.
#' @description Dj_index calculates METabolome SPECialization (δj) index based on Shannon entropy.
#'
#' @details
#' Metabolome specialization δj is measured for each jth sample, as the average of the metabolites' specificities.
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#' @return A data frame with the δj per species;

#' @export
#'
#' @examples Dj_df <- Dj_index (Data)


Dj_index <- function (Data){
  # Mssg
  print("THIS PARAMETER CAN NOT BE EXTRAPOLATED TO OTHER DATA SETS OR SUBSETS")

  #Warnings
  if (nrow(Data)<ncol(Data)) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  if (is.data.frame(Data) == FALSE) {
    warning('MetPlast functions takes as Data argument a data frame with compounds as observations -rows- and individual samples as variables -columns-')
  }

  #Stop
  if (any(is.na(Data))) {
    stop('NA values MUST be replace with Data[is.na(Data)] <- (min(Data, na.rm=TRUE))/1000000')
  }
  if (exists("Pij_by_Pi_fc") == FALSE) {
    stop('Internal function Pij_by_Pi_fc is not uploaded. Please, check MetPlast_int.R functions are properly uploaded.')
  }

  if (exists("Pij_fc") == FALSE) {
    stop('Internal function Pij_fc is not uploaded. Please, check MetPlast_int.R functions are properly uploaded.')
  }

  # Calculate metabolite specialization
  Pij_by_Pi <- Pij_by_Pi_fc (Data)
  Si <- apply(Pij_by_Pi, MARGIN = 1, FUN = Si_fc)

  # Calculate metabolome specialization
  Pij <- Pij_fc (Data)
  Pij_Si <- sweep(Pij, MARGIN = 1, Si, FUN = "*")
  Pij_Si_df <- data.frame(Pij_Si)
  Dj <- apply(Pij_Si_df, MARGIN = 2,  FUN = sum)

  #Output metabolome specilization
  Dj_df <- data.frame (Dj)
  Dj_Sample_df <- setDT(Dj_df, keep.rownames = "Sample")
  Dj_Sample_df$Sample <- sub("\\_?\\.?\\d+", "", Dj_Sample_df$Sample)
  Dj_Sample_df$Sample <- sub("\\..", ".", Dj_Sample_df$Sample)
  print(Dj_Sample_df)
}

#' Metabolome (δj) Specialization Index Plot
#'
#' @param Dj_df a data frame with the Dj values -column- for all the samples.
#' @param ... any other argument
#' @description Dj_index_plot calculates METabolome SPECialization (δj) index based on Shannon entropy.
#'
#' @details
#' Metabolome (δj) Specialization Index Plot generates a graph that shows the distrubution of the Specialization index among the samples (j).
#'
#' @author Lucio D'Andrea, PhD; Prof Aureliano Bombarely
#'
#' @return It returns a dot plot
#'
#'
#'
#' @export
#'
#' @examples  \dontrun{Dj_plot <- Dj_index_plot (Dj_df)}

Dj_index_plot <- function(Dj_df, ...) {
  #Warnings
  if (is.data.frame(Dj_df) == FALSE) {
    warning('Dj_index_plot functions takes as Dj_df argument a data frame')
  }

  #Stops
  if (exists("Dj_df") == FALSE) {
    stop('Dj_df should be provided. Please, run and store Dj_index(). Dj_df <- Dj_index()')
  }

  ggplot2::ggplot(Dj_df, aes(x=.data[["Sample"]], y = .data[["Dj"]], color = .data[["Sample"]], ...)) + geom_point() + geom_boxplot()

}
